// ---- Flashcard decks: quick term/definition review, one deck per section ----
window.FLASHCARDS = {
  basics: [
    { id: 'fc-basics-lan', term: 'LAN', def: 'A network of computers close together, like everyone in one building.' },
    { id: 'fc-basics-soho', term: 'SOHO', def: 'A tiny network setup for a home or small office &mdash; just a few devices, one router.' },
    { id: 'fc-basics-enterprise', term: 'Enterprise network', def: 'A large company network with hundreds or thousands of devices and dedicated equipment.' },
    { id: 'fc-basics-datacenter', term: 'Datacenter', def: 'A network built just for computers to talk to other computers, running nonstop.' },
    { id: 'fc-basics-osi', term: 'OSI model', def: 'The 7-layer map for how data moves from one device to another.' },
    { id: 'fc-basics-switch', term: 'Switch', def: 'Connects devices within ONE local network, using MAC addresses.' },
    { id: 'fc-basics-router', term: 'Router', def: 'Connects DIFFERENT networks together, using IP addresses.' },
    { id: 'fc-basics-packet', term: 'Packet', def: 'A small chopped-up piece of data sent across a network.' },
    { id: 'fc-basics-modem', term: 'Modem', def: "Turns the internet company's incoming signal into data your equipment understands." },
    { id: 'fc-basics-mac', term: 'MAC address', def: "A permanent hardware \"name tag\" burned into a device &mdash; it never changes." },
    { id: 'fc-basics-ip', term: 'IP address', def: 'A logical address that can change depending on which network a device connects to.' },
    { id: 'fc-basics-subnetting', term: 'Subnetting', def: 'Splitting one big network into smaller, safer, more organized groups.' },
    { id: 'fc-basics-ipv4', term: 'IPv4', def: 'A 32-bit address like 192.168.1.1; only about 4.3 billion of them exist.' },
    { id: 'fc-basics-ipv6', term: 'IPv6', def: 'A much longer address format with basically unlimited addresses available.' },
  ],
  topologies: [
    { id: 'fc-topo-p2p', term: 'Peer-to-peer (P2P)', def: 'Every device is equal &mdash; no central computer is in charge.' },
    { id: 'fc-topo-clientserver', term: 'Client-server', def: 'One computer (the server) provides resources to every other device (the clients).' },
    { id: 'fc-topo-man', term: 'MAN', def: 'A network that covers a whole city, connecting several LANs together.' },
    { id: 'fc-topo-wan', term: 'WAN', def: 'A network covering huge distances &mdash; the internet is the biggest WAN of all.' },
    { id: 'fc-topo-bus', term: 'Bus topology', def: 'All devices share one central cable; rarely used today.' },
    { id: 'fc-topo-ring', term: 'Ring topology', def: 'Devices connect in a circle; data travels around the loop.' },
    { id: 'fc-topo-star', term: 'Star topology', def: 'Every device connects to one central hub &mdash; the shape almost everyone uses today.' },
    { id: 'fc-topo-mesh', term: 'Mesh topology', def: 'Devices connect to many others directly, for maximum reliability.' },
    { id: 'fc-topo-iaas', term: 'IaaS', def: 'Renting raw computing hardware (servers, storage) from a cloud provider.' },
    { id: 'fc-topo-paas', term: 'PaaS', def: 'A ready-made platform for building and deploying apps without managing servers.' },
    { id: 'fc-topo-saas', term: 'SaaS', def: 'Fully finished software you just use over the internet, like Gmail.' },
    { id: 'fc-topo-5g', term: '5G', def: 'The newest cell network generation: much faster, low delay, tons of connected devices.' },
  ],
  security: [
    { id: 'fc-sec-vulnerability', term: 'Vulnerability', def: 'A weak spot in a system.' },
    { id: 'fc-sec-threat', term: 'Threat', def: 'Someone or something that could exploit a weak spot.' },
    { id: 'fc-sec-exploit', term: 'Exploit', def: 'The actual act of taking advantage of a weak spot.' },
    { id: 'fc-sec-risk', term: 'Risk', def: 'How worried you should be overall &mdash; likelihood plus impact.' },
    { id: 'fc-sec-zeroday', term: 'Zero-day', def: 'A brand-new security flaw with no fix available yet.' },
    { id: 'fc-sec-leastprivilege', term: 'Least privilege', def: 'Giving users only the access they truly need, and nothing more.' },
    { id: 'fc-sec-encryption', term: 'Encryption', def: 'Scrambling data so only someone with the right key can read it.' },
    { id: 'fc-sec-dos', term: 'DoS attack', def: 'Flooding a system with traffic from one source until it can\'t respond.' },
    { id: 'fc-sec-ddos', term: 'DDoS attack', def: 'A DoS attack launched from a huge botnet of hijacked devices at once.' },
    { id: 'fc-sec-phishing', term: 'Phishing', def: 'A fake message tricking you into giving up info or clicking something dangerous.' },
    { id: 'fc-sec-spoofing', term: 'Spoofing', def: 'Disguising a message or device to pretend it\'s from someone trusted.' },
    { id: 'fc-sec-dnspoisoning', term: 'DNS poisoning', def: 'Feeding a DNS resolver false records to redirect users to a fake site.' },
    { id: 'fc-sec-cia', term: 'CIA triad', def: 'Confidentiality, Integrity, Availability &mdash; the three things security protects.' },
    { id: 'fc-sec-hashing', term: 'Hashing', def: 'Turning data into a fingerprint-like code to prove it wasn\'t changed.' },
    { id: 'fc-sec-certificate', term: 'Digital certificate', def: 'An ID card for a website, proving it\'s really who it says it is.' },
    { id: 'fc-sec-mfa', term: 'MFA', def: 'Proving your identity with two different kinds of proof, like a password plus a fingerprint.' },
  ],
  protocols: [
    { id: 'fc-proto-ftp', term: 'FTP', def: 'Moves files between systems, but sends everything in plain text &mdash; not secure.' },
    { id: 'fc-proto-sftp', term: 'SFTP', def: 'The secure, encrypted version of FTP.' },
    { id: 'fc-proto-dns', term: 'DNS', def: 'Turns a website name like google.com into its numeric IP address.' },
    { id: 'fc-proto-dhcp', term: 'DHCP', def: 'Automatically hands out IP addresses to new devices joining a network.' },
    { id: 'fc-proto-80211', term: '802.11', def: 'The IEEE rulebook that defines Wi-Fi.' },
    { id: 'fc-proto-8023', term: '802.3', def: 'The IEEE rulebook that defines wired Ethernet.' },
    { id: 'fc-proto-tcp', term: 'TCP', def: 'Careful, reliable delivery &mdash; checks that everything arrived, in order.' },
    { id: 'fc-proto-udp', term: 'UDP', def: 'Fast delivery with no guarantees &mdash; used for streaming and gaming.' },
    { id: 'fc-proto-bgp', term: 'BGP', def: 'The routing protocol that runs the internet itself, between different networks.' },
    { id: 'fc-proto-nat', term: 'NAT', def: 'Lets many devices on a private network share one public IP address.' },
    { id: 'fc-proto-port443', term: 'Port 443', def: 'The well-known port for secure, encrypted web traffic (HTTPS).' },
    { id: 'fc-proto-wpa3', term: 'WPA3', def: 'The newest, strongest Wi-Fi encryption standard.' },
  ],
  hardware: [
    { id: 'fc-hw-nic', term: 'NIC', def: 'The chip that lets a device physically connect to a network.' },
    { id: 'fc-hw-utp', term: 'UTP cable', def: 'The standard, cheapest kind of Ethernet cable, with no extra shielding.' },
    { id: 'fc-hw-stp', term: 'STP cable', def: 'Ethernet cable with an extra metal shield against interference.' },
    { id: 'fc-hw-fiber', term: 'Fiber optic', def: 'Cable that sends data as pulses of light through glass instead of electricity.' },
    { id: 'fc-hw-singlemode', term: 'Single-mode fiber', def: 'A thin fiber strand built for very long distances, like between cities.' },
    { id: 'fc-hw-multimode', term: 'Multi-mode fiber', def: 'A wider, cheaper fiber strand for shorter runs, like inside a building.' },
    { id: 'fc-hw-rack', term: 'Rack server', def: 'A standalone server in its own case, mounted in a rack.' },
    { id: 'fc-hw-blade', term: 'Blade server', def: 'A thin server sharing power and cooling with others in one shared chassis.' },
    { id: 'fc-hw-nas', term: 'NAS', def: 'Dedicated network storage that lets everyone share files easily.' },
    { id: 'fc-hw-raid', term: 'RAID', def: 'Combining multiple hard drives together for more speed and/or safety.' },
  ],
};
